version: '3'

networks:
  backend-dev:
    driver: bridge
    external: true

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend-dev
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./docker/php/99-xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
    ports:
      - "9000:9000"
    networks:
      - backend-dev
    environment:
      PHP_IDE_CONFIG: serverName=Docker